// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetReconciliation():Promise<main.ReconciliationResult>;

export function PreviewPivot(arg1:main.PivotConfig):Promise<main.PivotResult>;

export function RemoveOutboundFile(arg1:string):Promise<void>;

export function ResetSession():Promise<void>;

export function SaveReport(arg1:main.PivotConfig,arg2:boolean):Promise<main.SaveResult>;

export function SelectOutboundFile():Promise<main.OutboundImportResult>;

export function SelectSourceFile():Promise<main.ImportResult>;
