// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetReconciliation() {
  return window['go']['main']['App']['GetReconciliation']();
}

export function PreviewPivot(arg1) {
  return window['go']['main']['App']['PreviewPivot'](arg1);
}

export function RemoveOutboundFile(arg1) {
  return window['go']['main']['App']['RemoveOutboundFile'](arg1);
}

export function ResetSession() {
  return window['go']['main']['App']['ResetSession']();
}

export function SaveReport(arg1, arg2) {
  return window['go']['main']['App']['SaveReport'](arg1, arg2);
}

export function SelectOutboundFile() {
  return window['go']['main']['App']['SelectOutboundFile']();
}

export function SelectSourceFile() {
  return window['go']['main']['App']['SelectSourceFile']();
}
